create table t_veiculo(
    id number generated by default as identity,
    dono varchar2(100),
    marca varchar2(100),
    modelo varchar2(100),
    placa varchar2(10),
    ano number(4),
    primary key(id)
);

create table t_ordemservico(
    id number generated by default as identity,
    data date,
    descricao varchar2(400),
    mecanico varchar2(100),
    valor number(8, 2),
    veiculo_id number,
    foreign key(veiculo_id) references t_veiculo(id),
    primary key(id)
);


