create table tbw_paciente(
    id number generated by default as identity,
    nome varchar2(100),
    documento varchar2(30),
    telefone varchar2(20),
    nascimento date,
    primary key(id)
);

create table tbw_funcionario(
    id number generated by default as identity,
    nome varchar2(100),
    cargo varchar2(50),
    registro varchar2(20),
    primary key(id)
);

create table tbw_triagem(
    id number generated by default as identity,
    datahora timestamp,
    temperatura number(3, 1),
    pressao number(3, 1),
    batimentos number,
    motivo varchar2(200),
    id_doente number,
    id_enfermeira number,
    primary key(id),
    foreign key(id_doente) references tbw_paciente(id),
    foreign key(id_enfermeira) references tbw_funcionario(id)
);

create table tbw_atendimento(
    id number generated by default as identity,
    datahora timestamp,
    tipo varchar2(50),
    descricao varchar2(200),
    id_doente number,
    id_funcionario number,
    primary key(id),
    foreign key(id_doente) references tbw_paciente(id),
    foreign key(id_funcionario) references tbw_funcionario(id)
);





