package br.com.fiap.dao;

import br.com.fiap.model.Tarefa;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.time.LocalDate;

public class TarefaDao {

    public void insere(Tarefa t) throws Exception {

        String sql = "insert into tarefa(titulo, descricao, status, " +
                "inicio, fim, prioridade) values(?, ?, ?, ?, ?, ?)";

        try(Connection con = new Conexao().getConexao();
            PreparedStatement pstmt = con.prepareStatement(sql);) {
            pstmt.setString(1, t.getTitulo());
            pstmt.setString(2, t.getDescricao());
            pstmt.setString(3, t.getStatus());
            pstmt.setDate(4, Date.valueOf(t.getInicio()));
            pstmt.setDate(5, Date.valueOf(t.getFim()));
            pstmt.setInt(6, t.getPrioridade());

            pstmt.executeUpdate();
        }
        catch(Exception e) {
            e.printStackTrace();
            throw e;
        }
    }

    public static void main(String[] args) {
        /*
        create table tarefa(id number generated by default as identity,
            titulo varchar2(80),
            descricao varchar2(200),
            status varchar2(50),
            inicio  date,
            fim date,
            prioridade number,
            primary key(id));
        */
        Tarefa teste = new Tarefa();
        teste.setTitulo("Checkpoint 5");
        teste.setDescricao("Conteudo de banco de dados");
        teste.setStatus("Incompleto!");
        teste.setInicio(LocalDate.of(2024, 10, 3));
        teste.setFim(LocalDate.of(2024, 10, 13));
        teste.setPrioridade(10);

        TarefaDao banco = new TarefaDao();
        try {
            banco.insere(teste);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
